### ISSUE TITLE
Gui Crash w/ Apple Skin

### ISSUE THREAD

**Issue by Fortist** [Snownee/Cuisine#37]
I decided to flip though the book you have so far, and it crashes when I look at the sesame oil page

```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2019-02-02 16:51:57 EST
Description: Rendering screen

java.lang.NullPointerException
    at snownee.kiwi.client.AdvancedFontRenderer.getStringWidth(AdvancedFontRenderer.java:374)
    at squeek.appleskin.client.TooltipOverlayHandler.onRenderTooltip(TooltipOverlayHandler.java:104)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2614_TooltipOverlayHandler_onRenderTooltip_PostText.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:409)
    at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:252)
    at net.minecraft.client.gui.GuiScreen.drawHoveringText(GuiScreen.java:182)
    at vazkii.patchouli.client.book.gui.GuiBook.drawTooltip(GuiBook.java:204)
    at vazkii.patchouli.client.book.gui.GuiBook.drawScreenAfterScale(GuiBook.java:142)
    at vazkii.patchouli.client.book.gui.GuiBook.drawScreen(GuiBook.java:123)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
Other than that, the book seems fine.

**Comment by 3TUSK** [comment]
> I am not sure what's the intention of rendering `null` string, but at least it's something we can handle...

Keep this open until next new release.

**Comment by Snownee** [comment]
https://minecraft.curseforge.com/projects/kiwi/files/2668371
