### ISSUE TITLE
can you release a forge_2768 version?

### ISSUE THREAD

**Issue by Jecvay** [Snownee/Cuisine#43]
As SpongeForge's stable version is 2768
upgrade forge version on server may cause plugin's some function's obf-mapping error

**Comment by liach** [comment]
spongeforge可以在更新的forge上用啊。新版本forge有几个重要功能和bug修复，所以mod都用新的forge。

**Comment by Jecvay** [comment]
@liach 为啥总能碰到你哈哈哈

**Comment by Jecvay** [comment]
@liach 只是略有担心 sponge 在 mapping 混淆函数的时候因为 forge 版本对不上 导致查不出来的诡异小问题

**Comment by liach** [comment]
sponge有这种问题？spongeforge针对新版本forge兼容失败的一般解决办法就是到sf叫sponge提升针对的forge版本。而且现在大多数forge的变动都是backward compatible的，应该不会有大问题。

**Comment by Jecvay** [comment]
> 现在大多数forge的变动都是backward compatible的
这个确实

**Comment by 3TUSK** [comment]
Mapping 和 forge 版本无关，此问题的理由不成立。

但是这个问题…… 我忽然有一个新的想法……

**Comment by liach** [comment]
不是mappings，他的意思是forge的新变动会让sponge一些mixin坏掉导致bug

**Comment by 3TUSK** [comment]
> may cause plugin's some function's obf-mapping error

**Comment by chenxuuu** [comment]
同求2768版本
现在为了兼容料理工艺，服务器用的2772版本
感觉这个forge版本有个bug能导致sponge崩服，还在确认原因

**Comment by 3TUSK** [comment]
> 感觉这个forge版本有个bug能导致sponge崩服

请给出崩溃报告或对应的服务器日志（`fml-debug.log`）。

**Comment by chenxuuu** [comment]
> > 感觉这个forge版本有个bug能导致sponge崩服
> 
> 请给出崩溃报告或对应的服务器日志（`fml-debug.log`）。

嘛，我是指高版本的forge导致的，不是指这个mod导致bug
具体的还在测试，不清楚具体原因

**Comment by chenxuuu** [comment]
崩服倒是没复现，但是刷了这东西

```log
[22:18:04] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/D:/1.12.2-SpongeForge/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0) called from class snownee.cuisine.items.ItemFan (loaded from jar:file:/D:/1.12.2-SpongeForge/./mods/%5B料理工艺%5DCuisine-0.5.0-build838.jar!/snownee/cuisine/items/ItemFan.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0).
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_202]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_202]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:301) [SpongeImplHooks.class:1.12.2-2768-7.1.6-RC3629]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjn000(MinecraftServer.java:3955) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]
Caused by: java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/D:/1.12.2-SpongeForge/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0) called from class snownee.cuisine.items.ItemFan (loaded from jar:file:/D:/1.12.2-SpongeForge/./mods/%5B料理工艺%5DCuisine-0.5.0-build838.jar!/snownee/cuisine/items/ItemFan.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0).
        at snownee.cuisine.items.ItemFan.func_180614_a(ItemFan.java:54) ~[ItemFan.class:?]
        at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:2963) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1873) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zja000(NetHandlerPlayServer.java:2426) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.6-RC3629]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
[22:18:04] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/D:/1.12.2-SpongeForge/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0) called from class snownee.cuisine.items.ItemFan (loaded from jar:file:/D:/1.12.2-SpongeForge/./mods/%5B料理工艺%5DCuisine-0.5.0-build838.jar!/snownee/cuisine/items/ItemFan.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0).
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_202]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_202]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:301) [SpongeImplHooks.class:1.12.2-2768-7.1.6-RC3629]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjn000(MinecraftServer.java:3955) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]
Caused by: java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/D:/1.12.2-SpongeForge/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0) called from class snownee.cuisine.items.ItemFan (loaded from jar:file:/D:/1.12.2-SpongeForge/./mods/%5B料理工艺%5DCuisine-0.5.0-build838.jar!/snownee/cuisine/items/ItemFan.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0).
        at snownee.cuisine.items.ItemFan.func_180614_a(ItemFan.java:54) ~[ItemFan.class:?]
        at snownee.cuisine.items.ItemFan.func_77659_a(ItemFan.java:43) ~[ItemFan.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:957) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClick$zja000(NetHandlerPlayServer.java:2448) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.6-RC3629]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
[22:18:05] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/D:/1.12.2-SpongeForge/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0) called from class snownee.cuisine.items.ItemFan (loaded from jar:file:/D:/1.12.2-SpongeForge/./mods/%5B料理工艺%5DCuisine-0.5.0-build838.jar!/snownee/cuisine/items/ItemFan.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0).
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_202]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_202]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:301) [SpongeImplHooks.class:1.12.2-2768-7.1.6-RC3629]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjn000(MinecraftServer.java:3955) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]
Caused by: java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/D:/1.12.2-SpongeForge/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0) called from class snownee.cuisine.items.ItemFan (loaded from jar:file:/D:/1.12.2-SpongeForge/./mods/%5B料理工艺%5DCuisine-0.5.0-build838.jar!/snownee/cuisine/items/ItemFan.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0).
        at snownee.cuisine.items.ItemFan.func_180614_a(ItemFan.java:54) ~[ItemFan.class:?]
        at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:2963) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1873) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zja000(NetHandlerPlayServer.java:2426) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.6-RC3629]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
[22:18:05] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/D:/1.12.2-SpongeForge/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0) called from class snownee.cuisine.items.ItemFan (loaded from jar:file:/D:/1.12.2-SpongeForge/./mods/%5B料理工艺%5DCuisine-0.5.0-build838.jar!/snownee/cuisine/items/ItemFan.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0).
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_202]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_202]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:301) [SpongeImplHooks.class:1.12.2-2768-7.1.6-RC3629]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjn000(MinecraftServer.java:3955) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]
Caused by: java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/D:/1.12.2-SpongeForge/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0) called from class snownee.cuisine.items.ItemFan (loaded from jar:file:/D:/1.12.2-SpongeForge/./mods/%5B料理工艺%5DCuisine-0.5.0-build838.jar!/snownee/cuisine/items/ItemFan.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0).
        at snownee.cuisine.items.ItemFan.func_180614_a(ItemFan.java:54) ~[ItemFan.class:?]
        at snownee.cuisine.items.ItemFan.func_77659_a(ItemFan.java:43) ~[ItemFan.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:957) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClick$zja000(NetHandlerPlayServer.java:2448) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.6-RC3629]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
[22:18:05] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/D:/1.12.2-SpongeForge/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0) called from class snownee.cuisine.items.ItemFan (loaded from jar:file:/D:/1.12.2-SpongeForge/./mods/%5B料理工艺%5DCuisine-0.5.0-build838.jar!/snownee/cuisine/items/ItemFan.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0).
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_202]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_202]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:301) [SpongeImplHooks.class:1.12.2-2768-7.1.6-RC3629]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjn000(MinecraftServer.java:3955) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]
Caused by: java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/D:/1.12.2-SpongeForge/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0) called from class snownee.cuisine.items.ItemFan (loaded from jar:file:/D:/1.12.2-SpongeForge/./mods/%5B料理工艺%5DCuisine-0.5.0-build838.jar!/snownee/cuisine/items/ItemFan.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0).
        at snownee.cuisine.items.ItemFan.func_180614_a(ItemFan.java:54) ~[ItemFan.class:?]
        at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:2963) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1873) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zja000(NetHandlerPlayServer.java:2426) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.6-RC3629]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
[22:18:05] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/D:/1.12.2-SpongeForge/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0) called from class snownee.cuisine.items.ItemFan (loaded from jar:file:/D:/1.12.2-SpongeForge/./mods/%5B料理工艺%5DCuisine-0.5.0-build838.jar!/snownee/cuisine/items/ItemFan.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0).
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_202]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_202]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:301) [SpongeImplHooks.class:1.12.2-2768-7.1.6-RC3629]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjn000(MinecraftServer.java:3955) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]
Caused by: java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/D:/1.12.2-SpongeForge/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0) called from class snownee.cuisine.items.ItemFan (loaded from jar:file:/D:/1.12.2-SpongeForge/./mods/%5B料理工艺%5DCuisine-0.5.0-build838.jar!/snownee/cuisine/items/ItemFan.class by net.minecraft.launchwrapper.LaunchClassLoader@88f418c0).
        at snownee.cuisine.items.ItemFan.func_180614_a(ItemFan.java:54) ~[ItemFan.class:?]
        at snownee.cuisine.items.ItemFan.func_77659_a(ItemFan.java:43) ~[ItemFan.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:957) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClick$zja000(NetHandlerPlayServer.java:2448) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.6-RC3629]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
```

**Comment by Snownee** [comment]
@chenxuuu 这个和版本没关系，Git上面已经修复了，然而没人发布新版本 🤷‍♂️

**Comment by 3TUSK** [comment]
> 刷了这东西
https://github.com/Snownee/Cuisine/commit/e6a4f16e4090342c3c72edd58e969475225293b5
@Snownee 你要是想的话，今天就可以有一个 0.5.1。

**Comment by Snownee** [comment]
@3TUSK 据我所知模型还是悬空的吧

**Comment by 3TUSK** [comment]
*sigh*
